//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Example.Implementation.Models
{
	/// <summary>Base</summary>
	[PublishedContentModel("Base")]
	public partial class Base : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Base";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Base(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Base, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Browser Titel
		///</summary>
		[ImplementPropertyType("browserTitel")]
		public string BrowserTitel
		{
			get { return this.GetPropertyValue<string>("browserTitel"); }
		}

		///<summary>
		/// Canonical tag
		///</summary>
		[ImplementPropertyType("canonicalTag")]
		public string CanonicalTag
		{
			get { return this.GetPropertyValue<string>("canonicalTag"); }
		}

		///<summary>
		/// Intro
		///</summary>
		[ImplementPropertyType("intro")]
		public string Intro
		{
			get { return this.GetPropertyValue<string>("intro"); }
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("mainBody")]
		public IHtmlString MainBody
		{
			get { return this.GetPropertyValue<IHtmlString>("mainBody"); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return this.GetPropertyValue<string>("metaDescription"); }
		}

		///<summary>
		/// Meta keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return this.GetPropertyValue<string>("metaKeywords"); }
		}

		///<summary>
		/// Meta robots
		///</summary>
		[ImplementPropertyType("metaRobots")]
		public bool MetaRobots
		{
			get { return this.GetPropertyValue<bool>("metaRobots"); }
		}

		///<summary>
		/// Thumbnail
		///</summary>
		[ImplementPropertyType("thumbnail")]
		public Muffin.Core.Models.ICropImageModel Thumbnail
		{
			get { return this.GetPropertyValue<Muffin.Core.Models.ICropImageModel>("thumbnail"); }
		}

		///<summary>
		/// Titel
		///</summary>
		[ImplementPropertyType("titel")]
		public string Titel
		{
			get { return this.GetPropertyValue<string>("titel"); }
		}

		///<summary>
		/// Verbergen in menu: Verbergen in menu weergave.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}

		///<summary>
		/// Widget Area
		///</summary>
		[ImplementPropertyType("widgetArea")]
		public IEnumerable<Muffin.Core.Models.DynamicMacroModel> WidgetArea
		{
			get { return this.GetPropertyValue<IEnumerable<Muffin.Core.Models.DynamicMacroModel>>("widgetArea"); }
		}
	}
}
