//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Example.Implementation.Models
{
	/// <summary>CarrouselItem</summary>
	[PublishedContentModel("CarrouselItem")]
	public partial class CarrouselItem : ContainerItemBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "CarrouselItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarrouselItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarrouselItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Afbeelding
		///</summary>
		[ImplementPropertyType("afbeelding")]
		public Muffin.Core.Models.ICropImageModel Afbeelding
		{
			get { return this.GetPropertyValue<Muffin.Core.Models.ICropImageModel>("afbeelding"); }
		}

		///<summary>
		/// Beschrijving
		///</summary>
		[ImplementPropertyType("beschrijving")]
		public string Beschrijving
		{
			get { return this.GetPropertyValue<string>("beschrijving"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public string Link
		{
			get { return this.GetPropertyValue<string>("link"); }
		}

		///<summary>
		/// Titel
		///</summary>
		[ImplementPropertyType("titel")]
		public string Titel
		{
			get { return this.GetPropertyValue<string>("titel"); }
		}
	}
}
