//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Example.Implementation.Models
{
	/// <summary>Content</summary>
	[PublishedContentModel("Content")]
	public partial class Content : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Content";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Content(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Content, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// CroppedImage
		///</summary>
		[ImplementPropertyType("croppedimage")]
		public Muffin.Core.Models.ICropImageModel Croppedimage
		{
			get { return this.GetPropertyValue<Muffin.Core.Models.ICropImageModel>("croppedimage"); }
		}

		///<summary>
		/// Grid
		///</summary>
		[ImplementPropertyType("Grid")]
		public Muffin.Core.Models.GridModel Grid
		{
			get { return this.GetPropertyValue<Muffin.Core.Models.GridModel>("Grid"); }
		}
	}
}
