//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Example.Implementation.Models
{
	/// <summary>Home</summary>
	[PublishedContentModel("Home")]
	public partial class Home : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carrousel Container: Container met carrousel items
		///</summary>
		[ImplementPropertyType("carrouselContainer")]
		public Muffin.Core.Models.IModel CarrouselContainer
		{
			get { return this.GetPropertyValue<Muffin.Core.Models.IModel>("carrouselContainer"); }
		}

		///<summary>
		/// QuickMenu
		///</summary>
		[ImplementPropertyType("quickmenu")]
		public IEnumerable<Muffin.Core.Models.IModel> Quickmenu
		{
			get { return this.GetPropertyValue<IEnumerable<Muffin.Core.Models.IModel>>("quickmenu"); }
		}

		///<summary>
		/// Social Networks
		///</summary>
		[ImplementPropertyType("socialNetworks")]
		public IEnumerable<Muffin.Core.Models.LinkModel> SocialNetworks
		{
			get { return this.GetPropertyValue<IEnumerable<Muffin.Core.Models.LinkModel>>("socialNetworks"); }
		}
	}
}
