//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Example.Implementation.Models
{
	/// <summary>Landing</summary>
	[PublishedContentModel("Landing")]
	public partial class Landing : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Landing";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Landing(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Landing, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Afbeelding Tekst: Tekst wordt gebruikt als overlay voor de afbeelding welke als banner dient op een landingspagina.
		///</summary>
		[ImplementPropertyType("afbeeldingTekst")]
		public string AfbeeldingTekst
		{
			get { return this.GetPropertyValue<string>("afbeeldingTekst"); }
		}
	}
}
